import Head from "next/head";
import Image from "next/image";
import { ChangeEvent, FormEvent, useState } from "react";
import styles from "../styles/Home.module.css";

type Talk = {
  title: string;
  abstract: string;
};
type Status = "Idle" | "Submitted" | "Complete"; // Union Type vs Enum
type Errors = {
  title: string,
  abstract: string
}
const newTalk: Talk = {
  title: "",
  abstract: "",
};

export default function Home() {
  const [status, setStatus] = useState<Status>("Idle"); //uses Generics
  const [talk, setTalk] = useState(newTalk);
  const [talks, setTalks] = useState<Talk[]>([]);
  const errors = validate();
  function onChange(event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) {
    setTalk({ ...talk, [event.target.id]: event.target.value });
  }

  function handleSubmit(event:FormEvent<HTMLFormElement>) {
    const isValid = Object.values(errors).filter(err => err).length == 0;
    event.preventDefault();
    if(!isValid) return;
    setStatus("Submitted");

    console.log('isValid', isValid);
    if(isValid) {
      setStatus("Complete")
      setTalk(newTalk);
    }
    console.log('..in handleSubmit', event.target);
    setTalks([...talks, talk]);
  }

  function validate() {
    const errors: Errors = {
      title: null,
      abstract: null
    };
    if (!talk.title) {
      errors.title = "Title is Required."
    }
    if (!talk.abstract) {
      errors.abstract = "Abstract is Required."
    }
    console.log('errors', errors);
    return errors;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>ConnectTech 2021</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Speak at ConnectTech!</h1>
        <section>
          <h2>Submitted Talks </h2>
          <ul>
        {talks.map(talk => {
          <li>{talk.title}</li>
        })}
        </ul>
        </section>

        <form onSubmit={handleSubmit}>
          <h2>Submit a talk</h2>
          <div>
            <label htmlFor="title">Title</label>
            <br />
            <input
              type="text"
              id="title"
              value={talk.title}
              onChange={onChange}
            />
            {errors.title && status === "Submitted" && <p> {errors.title} </p>}
          </div>
          <div>
            <label htmlFor="abstract">Abstract</label>
            <br />
            <textarea id="abstract" value={talk.abstract} onChange={onChange} />
            {errors.abstract && status === "Submitted" && <p> {errors.abstract} </p>}
          </div>
          <input type="submit" value="Submit talk" />
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
