import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
//command . for auto complete and auto import
type Talk = {
  title: string;
  abstract: string;
};
const newTalk: Talk = {
  title:'',
  abstract:''

};

export default function Home() {
  const [talk, setTalk] = useState(newTalk);
  function onChange(event :ChangeEvent<HTMLInputElement>) {
    console.log(event)
    setTalk({...talk, [event.target.id]: event.target.value});
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Connect Tech - 2021</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Speak at Connect.tech
        </h1>
        {/* What is the least amount of data in the form */}
        <form name="speakerForm" action="">
          <h2>Submit a Talk </h2>
          <div>
            <label htmlFor="title">Title</label>
            <br />
            <input type="text" name="title" value={talk.title} id="title" onChange={onChange}></input>
          </div>
          <div>
            <label htmlFor="abstract">Abstract</label>
            <br />
            <textarea id="abstract" value={talk.abstract}  onChange={onChange}></textarea>
          </div>
          <input type="submit" value='Submit Talk'></input>
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
